### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ryantpayton** [RajanGrewal/Client179#1]
This is not working for me. I downloaded the v179 client straight from the site. Any advice?

**Comment by ryantpayton** [comment]
Also for more background, it launches the "Nexon Security Client" and then crashes with an error.
https://cdn.discordapp.com/attachments/408294821393072129/697294302438490142/unknown.png

**Comment by RajanGrewal** [comment]
PC was down past few days, will take a look today.  Thanks for reporting

**Comment by ryantpayton** [comment]
No problem at all. Thanks for all your work :)

**Comment by RajanGrewal** [comment]
Confirmed the memory edits are valid , it seems your machine did not load the dll , so the mem patches didnt take effect.  Going to close for now as nothing wrong with the code.

I messaged you on discord btw :)
